name: Build Simulator

on: 
  push:
    branches: [master]
    paths: [simulator, .github/workflows]
  workflow_dispatch: {}

jobs:
  build-artifact:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        run: |
          corepack enable
      - name: Build
        run: |
          cd simulator
          pnpm install
          pnpm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: simulator
          path: simulator/build

  deploy-gh-pages:
    runs-on: ubuntu-22.04
    needs: build-artifact
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: simulator
        uses: actions/deploy-pages@v4
        with:
          artifact_name: simulator
          

  