name: Build Simulator

on: 
  push:
    branches: [master]
    paths: [simulator, .github/workflows]
  workflow_dispatch: {}

jobs:
  build-artifact:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          cd simulator
          pnpm install
          pnpm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: simulator
          path: simulator/build

  deploy-gh-pages:
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to Github Pages`
        run: echo "TODO!"

  