name: Build Simulator

on: 
  push:
    branches: [master]
    paths: [simulator, .github/workflows]
  workflow_dispatch: {}

jobs:
  build-artifact:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Environment
        run: |
          corepack enable
      - name: Build
        run: |
          cd simulator
          pnpm install
          pnpm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        id: deployment
        with:
          name: simulator
          path: simulator/build

  deploy-gh-pages:
    runs-on: ubuntu-22.04
    needs: build-artifact
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
          

  